language: objective-c
osx_image: xcode8.3
xcode_project: FourInARow.xcodeproj
xcode_scheme: FourInARow
xcode_sdk: iphonesimulator10.3

# Custom build and unit test scripts
script:
    - xcodebuild clean build-for-testing -sdk iphonesimulator10.3 -project FourInARow.xcodeproj -scheme FourInARow CODE_SIGNING_REQUIRED=NO
    - xctool -project FourInARow.xcodeproj -scheme FourInARow -sdk iphonesimulator10.3 run-tests
