language: objective-c
osx_image: xcode8.3

before_install:
  # Identify Simulator UUID
  - export IOS_SIMULATOR_UDID=`instruments -s devices | grep -m 1 "iPhone SE (10.3" | awk -F '[ ]' '{print $4}' | awk -F '[\[]' '{print $2}' | sed 's/.$//'`
  - echo $IOS_SIMULATOR_UDID
  - open -a "simulator" --args -CurrentDeviceUDID $IOS_SIMULATOR_UDID

script:
  # Custom build and unit test scripts
  - xcodebuild -project FourInARow.xcodeproj -scheme FourInARow CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator10.3 -destination "id=$IOS_SIMULATOR_UDID" clean build test | xcpretty -c
