language: objective-c
osx_image: xcode8.3
xcode_project: FourInARow.xcodeproj
xcode_scheme: FourInARow
xcode_sdk: iphonesimulator10.3

# somehow default behavior not working, refer https://stackoverflow.com/questions/41786984/error-unexpected-action-build-when-building-a-project-with-swift-3-and-cocoa
script:
    - xcodebuild clean build -sdk iphonesimulator10.3 -workspace FourInARow.xcworkspace -scheme FourInARowTests CODE_SIGNING_REQUIRED=NO
